### ISSUE TITLE
Add metadata function section to documentation

### ISSUE THREAD

**Issue by karenmajewicz** [geoblacklight/docs-archive#14]
The metadata schema(s) for GeoBlacklight are documented at OpenGeoMetadata.

However, we need more documentation on how those metadata fields & values function in the GeoBlacklight application.  Some things to look at:

- a list of which fields might break GeoBlacklight if they are missing or misconfigured
- which fields function as plain text strings in GBL
- which fields trigger some kind of action in GBL
-

**Comment by karenmajewicz** [comment]
related issue https://github.com/orgs/OpenGeoMetadata/projects/2/views/3?pane=issue&itemId=21571802

**Comment by mradamcox** [comment]
One idea for implementing this content would be to add a new section between "Installation" and "Customization," as someone suggested on the call yesterday. Something like "Configuration" could work, but this may get confusing because some of the topics in the Customization section are titled "Configuring...." 

Another approach could be to put it within the existing Metadata page, with a header like: "How GeoBlacklight Renders Metadata Fields."

**Comment by ewlarson** [comment]
Bill McKinney will participate

**Comment by karenmajewicz** [comment]
@bmckinney to review documentation

**Comment by karenmajewicz** [comment]
https://karenmajewicz.github.io/gbl-docs/metadata/

**Comment by karenmajewicz** [comment]
Add section on how to extend/customize fields

**Comment by karenmajewicz** [comment]
https://geoblacklight.org/docs/metadata/
